### ISSUE TITLE
Running program on different cupx file

### ISSUE THREAD

**Issue by llauner** [ubx/Landewiese-to-XCSoar-Waypoints#1]
Hi
I'm trying to execute your program on my own cupx file.
This seems to work for the provided .zup of .cupx file, but not on mine. It looks like the program will scan the data/ folder for cupx file and then process them ?
`
Input zip file(s):
 []
Input cpux file(s):
 ['guide_aires_securite.cupx']
Traceback (most recent call last):
  File "C:\Users\llauner\Downloads\_Test\Landewiese-to-XCSoar-Waypoints\convert.py", line 40, in <module>
    convert()
  File "C:\Users\llauner\Downloads\_Test\Landewiese-to-XCSoar-Waypoints\convert.py", line 25, in convert
    cnv.cpux2xcsoar(os.path.join(DATA_DIR, fn))
  File "C:\Users\llauner\Downloads\_Test\Landewiese-to-XCSoar-Waypoints\convert_cupx.py", line 38, in cpux2xcsoar
    with open(os.path.join(cupx_file_extracted_path, cup_file_name), 'r') as cup_file:
  File "C:\Program Files\Python310\lib\ntpath.py", line 143, in join
    genericpath._check_arg_types('join', path, *paths)
  File "C:\Program Files\Python310\lib\genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'
`

Can you try with my file ? it's available here:
https://planeur-net.github.io/outlanding/guide_aires_securite.cupx

Thanks

**Comment by ubx** [comment]
I can reproduce the problem and will look for a solution soon.

**Comment by ubx** [comment]
Problems:

1. The file `guide_aires_securite.cupx` must be in a zip file, for example,` guide_aires_securite.zip`.

2.  The extracted cup file contains bad lines:
- `"version=",4.1,,,,,,,,,,"5cf6dee 2023-12-27T16:29:40+01:00",,`
- `-----Related Tasks-----`

I made the program a little more tolerant to overcome the bad lines.

**Comment by llauner** [comment]
Thanks for the fix.
I think there's a problem as I'm not seeing any image in XCSoar. I've tried playing with the name / code as I noticed that the _details.txt file was using the code (the doc says the name shoudl be used ?), but I didn't manage to have any image displayed in the waypoint details page.
I copied the output directory where indicated, and populated the Waypoint and Waypoint details fields in XCSoar.
Any idea ?

**Comment by ubx** [comment]
It works on my Linux box and my Android phone:

![Screenshot_20231229-184652_XCSoar](https://github.com/ubx/Landewiese-to-XCSoar-Waypoints/assets/516680/3fe394c9-47c8-49df-b39f-ad918699975b)

![Screenshot_20231229-190251_XCSoar](https://github.com/ubx/Landewiese-to-XCSoar-Waypoints/assets/516680/dd4080c3-0fe8-4646-9dc3-ff2eb3c0da20)

![Screenshot_20231229-184800_XCSoar](https://github.com/ubx/Landewiese-to-XCSoar-Waypoints/assets/516680/9848536f-e6d8-4c7d-95fc-588aa9c98bd6)

![Screenshot_20231229-185059_File Manager +](https://github.com/ubx/Landewiese-to-XCSoar-Waypoints/assets/516680/cbfec84e-b2ed-47d1-9868-2583b9978f16)

**Comment by llauner** [comment]
I cannot make it work on my Android...
I have 4 files generated:
guide_aires_securite.cupx.cup
guide_aires_securite.wp_details.txt
landewisen.cup
landewisen_detatils.txt

Which one did you try with ?
Is the picture supposed to be displayed in the waypoint details ?
I'm running XCSoar 7.41

**Comment by ubx** [comment]
My description says:

``5. Run `python convert [<name>]`. The default name is *landewisen*``

So, you took the default, which is `landewisen.cup` and `landewisen_details.txt`

The images are in` pics/`

All files must reside in the same directory as the other XCSoar files, in my case, here:
![Screenshot from 2023-12-29 23-51-21](https://github.com/ubx/Landewiese-to-XCSoar-Waypoints/assets/516680/d333ba21-8d2c-4fda-906d-293fed580466)

>  Is the picture supposed to be displayed in the waypoint details ?

For instant, the code LFNS in`landewisen.cup`  references the picture `image=pics/LFNS_Sisteron_These.jpg` in  `landewisen_details.txt`.

For a description see [Waypoint Details, (Chapter 14.5)](https://download.xcsoar.org/releases/7.28/XCSoar-manual.pdf)

**Comment by llauner** [comment]
Yes, I have all of these.
It worked on the first try on the Windows version.
But on any of my 2 Android devices, I just don't see any picture in XCSoar. In the waypoint details, The page which is supposed to show the picture never appears when changing page with the bottom arrows.
The .log doesn't say anything.
Not sure what to do now !

I've just tried with very simple files: just 1 airport. Same result = does not display on my android device.
Find enclosed the files.
[output.zip](https://github.com/ubx/Landewiese-to-XCSoar-Waypoints/files/13797591/output.zip)

**Comment by llauner** [comment]
The problem has been found: https://forum.xcsoar.org/viewtopic.php?f=2&t=368&p=24479#p24479
In the details.txt file, the path separator should not be a \ but a /
This works on both PC and Android version.

Do you think you could do a fix ?
I also noticed a typo: the details file is called .detatils instead of .details

**Comment by ubx** [comment]
Fixed in a4cbcf241bb0fbd33fa528f7a1ce29afe18b86ef and 148016c45b816db571930a284adaf39fd6b172de
