### ISSUE TITLE
Do not see images on Android XCSoar v7.41

### ISSUE THREAD

**Issue by iamambrus** [ubx/Landewiese-to-XCSoar-Waypoints#2]
Hi, followed instructions and successfully generated a .cup and the details files. Copied them to the path advised (BTW tried under XCSoarData as well) to no success - while the waypoints load, none of the images do.

Examples (near LOKL):
"Gerlamoos (Kat A 2021)","GERL0318",AT,4645.577N,01316.759E,575m,3,080,500m,0m,,"Feld, Unebenheiten, Leitung(en)",,"1_318_osm.jpg;2_554.jpg"

[GERL0318]
image=pics/1_318_osm.jpg
image=pics/2_554.jpg

the file(s) do exists physically I checked. the path of the pics is Android/data/org.xcsoar/files/pics  The cup and details files are under Android/data/org.xcsoar/files.

I tried to see if XCSOar outputs any logfile, cannot see any information there.

Any ideas, please? Thanks a lot in advance. 

PS for reference here are the files I generated:
https://www.dropbox.com/scl/fo/6wzxmxokzhj6rjmcgwfnj/h?rlkey=fpcqztd08dafr4xxrktgfioui&dl=0

**Comment by ubx** [comment]
No problem here. On my Linux box, but should be the same on Android.
![Screenshot from 2024-02-25 10-02-22](https://github.com/ubx/Landewiese-to-XCSoar-Waypoints/assets/516680/e4b2de5b-af6e-4fd1-9c3e-dce881ac6dd2)![Screenshot from 2024-02-25 10-01-20](https://github.com/ubx/Landewiese-to-XCSoar-Waypoints/assets/516680/8a0870ff-cfbc-45bd-ad9b-c28a165e82ce)
![Screenshot from 2024-02-25 10-01-41](https://github.com/ubx/Landewiese-to-XCSoar-Waypoints/assets/516680/162cd11f-5e1c-44c6-ad1f-46bd9e98c71f)

**Comment by iamambrus** [comment]
Strange. in the meanwhile I tried [still on Android] XCSoar Jet 7.39 and that works. 7.41 still does not work. Friend of mind had the same issue and workaround to make it work. 
So this might be an XCSoar issue. your package is awesome, thanks for putting it together!

**Comment by ubx** [comment]
Tried it on Android 7.41, and it works as expected. Just out of curiosity, what was the workaround?

**Comment by iamambrus** [comment]
Per above Android XCSoar Jet 7.39 worked for me. Which is weird. Thanks!
